#!/bin/bash

WD=`pwd`

cd ../natlog
    build man
    build sourceforge || exit 1
cd $WD

yodl2html index.yo | exit 1

scp ../natlog/tmp/manhtml/*.html \
    index.html natlog.jpg \
    fbb,natlog@web.sourceforge.net:htdocs/

rm index.html

cd ../natlog
    build distclean

