#!/bin/bash

if [ $# -eq 0 ] ; then
    echo "provide (colon separated) protocol specs, or 'all'"
    echo "followed by 'in' 'out' device spec. or 'conntrack'"
    exit 0
fi

rm -f /tmp/natlog

tmp/bin/binary -t utc --no-daemon -s --log /tmp/natlog --protocol $*
